title: "PostGISトポロジー入門"
summary: "PostGISのトポロジーエクステンションを触ってみましょう。2020/12/25公開ですが、現在は2025/12/12公開の第2版です。"
topics: [PostGIS, GIS]
published: true
price: 0
# 本に含めるチャプターを順番に並べましょう
chapters:
#  - whatistopology
#  - editing
#  - columns
#  - topogeom
#  - simplify
  - whatis
  - build
  - inside
  - topogeo
  - layer
  - pref
  - conclusion
